name: "Discord Workflow Status Action"
description: "GitHub Action to notify Discord of workflow statuses"
author: "José Duarte"

inputs:
  strict:
    description: >
      Whether the action should fail or be successful when missing `discord-webhook`.
      This is useful to allow forks to run an actions suite.
    required: false
    default: true

  github-token:
    description: "GitHub Token"
    required: true

  discord-webhook:
    description: "Discord Webhook URL"
    required: false
    default: ""

  username:
    description: "Overrides the current username of the webhook"
    required: false
    default: "GitHub Actions"

  avatar-url:
    description: "Overrides the current avatar of the webhook"
    required: false
    default: "https://avatars0.githubusercontent.com/u/44036562?s=200&v=4"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "message-square"
  color: "gray-dark"
